### Year Stats sheet status

- Collected/loaded: yes
- Reviewed for usefulness: yes
- EDA needed: no, inspection only
- Cleaning/prep completed: yes, removed fully empty 2010 and 2011 rows
- Saved as separate prepared file: yes
- Ready for SQL/Tableau: yes, as helper/reference data
- Role: summary/reference dataset, not main analysis dataset

In [1]:
import pandas as pd

In [2]:
file_path = "../data/raw/public_ctwc_match_statistics.xlsx"

In [3]:
year_stats = pd.read_excel(file_path, sheet_name="Year Stats")
year_stats.head()

,Year,Total Games,Median Score,Transitions,Killscreens,Level 39s,Transition %,Killscreen %,Level 39%,Average Score,Average Win,Average Loss,Median Lines,Average Lines,Median 19 Trans,Median 29 Trans
0,2025,356.0,1028918.5,325.0,242.0,11.0,0.912921,0.679775,0.030899,986860.0618,1.046003e+06,927717.4944,245.0,233.309659,544600.0,1031520.0
1,2024,354.0,1000380.0,318.0,217.0,8.0,0.898305,0.612994,0.022599,938261.6384,9.883792e+05,888144.0339,238.0,221.435028,545740.0,1032700.0
2,2023,354.0,928482.5,304.0,189.0,6.0,0.858757,0.533898,0.016949,848542.2797,8.955919e+05,801492.6441,231.0,205.014124,543010.5,1024623.0
3,2022,346.0,827740.5,279.0,140.0,9.0,0.806358,0.404624,0.026012,772039.3988,8.156813e+05,728397.4971,212.5,190.809249,543231.0,1023210.0
4,2021,984.0,754400.0,777.0,281.0,2.0,0.789634,0.285569,0.002033,709364.6982,7.625043e+05,656225.1098,192.0,175.374745,525220.0,1001400.0

In [4]:
year_stats.shape

(16, 16)

In [5]:
year_stats.columns.tolist()

['Year',
 'Total Games',
 'Median Score',
 'Transitions',
 'Killscreens',
 'Level 39s',
 'Transition %',
 'Killscreen %',
 'Level 39%',
 'Average Score',
 'Average Win',
 'Average Loss',
 'Median Lines',
 'Average Lines',
 'Median 19 Trans',
 'Median 29 Trans']

In [6]:
year_stats.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             16 non-null     int64
 1   Total Games      14 non-null     float64
 2   Median Score     14 non-null     float64
 3   Transitions      14 non-null     float64
 4   Killscreens      14 non-null     float64
 5   Level 39s        14 non-null     float64
 6   Transition %     14 non-null     float64
 7   Killscreen %     14 non-null     float64
 8   Level 39%        14 non-null     float64
 9   Average Score    14 non-null     float64
 10  Average Win      14 non-null     float64
 11  Average Loss     14 non-null     float64
 12  Median Lines     14 non-null     float64
 13  Average Lines    14 non-null     float64
 14  Median 19 Trans  14 non-null     float64
 15  Median 29 Trans  14 non-null     float64
dtypes: float64(15), int64(1)
memory usage: 2.1 KB

In [7]:
year_stats[year_stats.isna().any(axis=1)]

,Year,Total Games,Median Score,Transitions,Killscreens,Level 39s,Transition %,Killscreen %,Level 39%,Average Score,Average Win,Average Loss,Median Lines,Average Lines,Median 19 Trans,Median 29 Trans
14,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
year_stats_clean = year_stats.dropna(how="all", subset=year_stats.columns[1:]).copy()
year_stats_clean

,Year,Total Games,Median Score,Transitions,Killscreens,Level 39s,Transition %,Killscreen %,Level 39%,Average Score,Average Win,Average Loss,Median Lines,Average Lines,Median 19 Trans,Median 29 Trans
0,2025,356.0,1028918.5,325.0,242.0,11.0,0.912921,0.679775,0.030899,986860.0618,1.046003e+06,927717.4944,245.0,233.309659,544600.0,1031520.0
1,2024,354.0,1000380.0,318.0,217.0,8.0,0.898305,0.612994,0.022599,938261.6384,9.883792e+05,888144.0339,238.0,221.435028,545740.0,1032700.0
2,2023,354.0,928482.5,304.0,189.0,6.0,0.858757,0.533898,0.016949,848542.2797,8.955919e+05,801492.6441,231.0,205.014124,543010.5,1024623.0
3,2022,346.0,827740.5,279.0,140.0,9.0,0.806358,0.404624,0.026012,772039.3988,8.156813e+05,728397.4971,212.5,190.809249,543231.0,1023210.0
4,2021,984.0,754400.0,777.0,281.0,2.0,0.789634,0.285569,0.002033,709364.6982,7.625043e+05,656225.1098,192.0,175.374745,525220.0,1001400.0
5,2020,940.0,603861.5,705.0,154.0,0.0,0.750000,0.163830,0.000000,589328.2128,6.398349e+05,538821.5574,167.0,158.493617,501260.0,971082.5
6,2019,256.0,472160.0,163.0,15.0,0.0,0.636719,0.058594,0.000000,452803.4453,4.820036e+05,423603.2734,147.0,136.410156,466740.0,815180.0
7,2018,174.0,466290.0,113.0,15.0,0.0,0.649425,0.086207,0.000000,454546.5862,4.900514e+05,419041.7241,148.0,142.442529,445088.0,833680.0
8,2017,98.0,454542.0,66.0,4.0,0.0,0.673469,0.040816,0.000000,426312.9898,4.566069e+05,396019.0408,144.0,139.897959,428906.0,732534.0
9,2016,90.0,475635.5,66.0,3.0,0.0,0.733333,0.033333,0.000000,447940.4444,4.842186e+05,411662.2889,157.0,151.864197,446471.5,724609.0
10,2015,90.0,439821.5,63.0,4.0,0.0,0.700000,0.044444,0.000000,401544.1667,4.303157e+05,372772.6000,148.0,139.344444,426948.0,661663.0
11,2014,50.0,463820.0,35.0,1.0,0.0,0.700000,0.020000,0.000000,446120.7600,4.875268e+05,404714.7600,164.0,153.404255,424530.0,601476.0
12,2013,40.0,471690.0,32.0,2.0,0.0,0.800000,0.050000,0.000000,431044.5250,4.565271e+05,405561.9500,163.0,152.775000,426937.0,674729.0
13,2012,34.0,439706.5,21.0,1.0,0.0,0.617647,0.029412,0.000000,381519.1471,4.335969e+05,329441.3529,181.0,150.911765,410267.0,660325.0

In [9]:
year_stats_clean.shape

(14, 16)

In [10]:
output_path = "../data/processed/ctwc_year_stats_cleaned.xlsx"
year_stats_clean.to_excel(output_path, index=False)

output_path

'../data/processed/ctwc_year_stats_cleaned.xlsx'