### Validation sheet status

- Collected/loaded: yes
- Reviewed for usefulness: yes
- EDA needed: no, inspection only
- Cleaning/prep completed: no
- Saved as separate prepared file: no
- Ready for SQL/Tableau: no
- Role: not used; mixed validation/helper sheet with no practical value as a clean dataset

In [3]:
import pandas as pd

In [4]:
file_path = "../data/raw/public_ctwc_match_statistics.xlsx"

In [5]:
validation = pd.read_excel(file_path, sheet_name="Validation")
validation.head()

,Years,Players,Country Code,Country,Unique Countries,Unnamed: 5,Sorted Countries,Unnamed: 7
0,Lifetime,All,All,All,All,NaN,All,NaN
1,2025,Adam Cornelius,USA,United States,United States,129.0,United States,129.0
2,2024,AdamMts,POL,Poland,Poland,1.0,Canada,11.0
3,2023,adudeabides,USA,United States,United Kingdom,8.0,United Kingdom,8.0
4,2022,Alex Kerr,USA,United States,Australia,2.0,Japan,4.0

In [6]:
validation.shape

(185, 8)

In [7]:
validation.columns.tolist()

['Years',
 'Players',
 'Country Code',
 'Country',
 'Unique Countries',
 'Unnamed: 5',
 'Sorted Countries',
 'Unnamed: 7']

In [8]:
validation.info()

<class 'pandas.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Years             17 non-null     object
 1   Players           185 non-null    str
 2   Country Code      185 non-null    str
 3   Country           185 non-null    str
 4   Unique Countries  30 non-null     str
 5   Unnamed: 5        40 non-null     float64
 6   Sorted Countries  30 non-null     str
 7   Unnamed: 7        40 non-null     float64
dtypes: float64(2), object(1), str(5)
memory usage: 11.7+ KB

In [10]:
validation["Players"].nunique()

185

In [11]:
validation["Players"].notna().sum()

np.int64(185)

In [13]:
validation.head(20)

,Years,Players,Country Code,Country,Unique Countries,Unnamed: 5,Sorted Countries,Unnamed: 7
0,Lifetime,All,All,All,All,NaN,All,NaN
1,2025,Adam Cornelius,USA,United States,United States,129.0,United States,129.0
2,2024,AdamMts,POL,Poland,Poland,1.0,Canada,11.0
3,2023,adudeabides,USA,United States,United Kingdom,8.0,United Kingdom,8.0
4,2022,Alex Kerr,USA,United States,Australia,2.0,Japan,4.0
5,2021,Alex T,USA,United States,Romania,1.0,Germany,3.0
6,2020,Alex_H,GBR,United Kingdom,Germany,3.0,Australia,2.0
7,2019,AnfonyHoe,AUS,Australia,Finland,2.0,Finland,2.0
8,2018,Anomalous,USA,United States,Canada,11.0,Iceland,2.0
9,2017,AnselTetris,USA,United States,Switzerland,1.0,Mexico,2.0
10,2016,armstrong,USA,United States,Japan,4.0,Sweden,2.0
11,2015,Asta,USA,United States,Colombia,1.0,Argentina,1.0
12,2014,atkoster,USA,United States,Greece,1.0,Austria,1.0
13,2013,AvGeekW159,USA,United States,Italy,1.0,Belgium,1.0
14,2012,B14NK,USA,United States,Belgium,1.0,Brazil,1.0
15,2011,Batfoy,USA,United States,Brazil,1.0,Colombia,1.0
16,2010,BeastinShen,USA,United States,Sweden,2.0,Greece,1.0
17,NaN,Ben Mullen,USA,United States,Portugal,1.0,Hong Kong,1.0
18,NaN,Bendy,USA,United States,Spain,1.0,Indonesia,1.0
19,NaN,Benjy,USA,United States,Philippines,1.0,Italy,1.0