### All Time Leaderboard Stats sheet status

- Collected/loaded: yes
- Reviewed for usefulness: yes
- EDA needed: no, inspection only
- Cleaning/prep completed: no
- Saved as separate prepared file: no
- Ready for SQL/Tableau: no
- Role: not used for now; all-time player summary sheet without a year dimension, so it does not support the main project red thread

In [1]:
import pandas as pd

In [2]:
file_path = "../data/raw/public_ctwc_match_statistics.xlsx"

In [11]:
all_time_leaderboard_stats = pd.read_excel(file_path, sheet_name="All Time Leaderboard Stats")
all_time_leaderboard_stats.head(20)

,Player,Total Games,Total Maxouts,Winning Percentage,Fair Median Score,High Range,Low Range,Fair Median 19 Trans,Fair Median 29 Trans,Fair Median Post,Fair 19%,Fair 29%,Fair 38%,Median Score,Upper Quartile,Lower Quartile,Median 19 Trans,Median 29 Trans,Median Post
0,Jonas,102,0,0.745098,636770.0,759390.00,513380.00,468503.0,177080.0,174460.0,0.954023,0.108108,0.0,577560.0,723200.00,461456.00,468645.0,932620.0,154770.0
1,Harry Hong,62,0,0.548387,574673.0,671366.75,450222.00,454572.0,372938.0,155283.0,0.888889,0.194444,0.0,528780.0,663476.50,429212.00,459080.0,697824.0,126580.0
2,Eli Markstrom,29,0,0.482759,474351.0,533979.00,385677.00,396031.0,350279.0,70511.0,0.875000,0.117647,0.0,411214.0,505763.00,350098.00,406637.0,692467.0,32523.0
3,Robin Mihara,14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ben Mullen,22,0,0.363636,496853.0,585540.00,430900.00,459480.0,NaN,97140.0,0.809524,0.000000,0.0,479660.0,541367.25,414955.00,465180.0,NaN,75071.5
5,Buco,31,0,0.483871,498061.0,637859.25,346058.25,371661.5,320639.5,156050.0,0.777778,0.190476,0.0,434537.0,633990.00,329894.00,423706.5,757149.5,143480.0
6,Dana Wilcox,10,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Alex Kerr,54,0,0.462963,512860.0,617644.50,377925.00,432746.0,226100.0,137640.0,0.745098,0.058824,0.0,456090.0,583434.00,257510.00,440866.0,757933.0,117240.0
8,Josh Tolles,29,0,0.379310,484080.0,635966.25,405721.75,386961.5,NaN,165120.0,0.769231,0.047619,0.0,467074.0,631230.00,397819.00,424120.0,NaN,105220.0
9,Quaid,66,0,0.545455,583036.0,671818.25,443090.00,421206.0,644310.0,197613.0,0.877193,0.263158,0.0,555940.5,671818.25,418901.25,431831.0,802320.0,187600.0
10,Bo Steil,11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Mike Winzinek,19,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Chad,28,0,0.464286,462010.5,534790.00,377005.00,401201.0,NaN,67740.0,0.909091,0.000000,0.0,439030.0,507840.00,351900.00,406700.0,NaN,29540.0
13,Jani Herlevi,33,0,0.393939,522624.5,602550.00,343140.00,399143.5,211665.0,97600.0,0.821429,0.142857,0.0,482200.0,592940.00,301120.00,418440.0,558187.0,77920.0
14,Trey Harrison,22,0,0.454545,418320.0,507962.00,369187.00,385651.0,NaN,37880.0,0.833333,0.000000,0.0,394540.0,432360.00,312160.00,394480.0,NaN,26260.0
15,Cameron Eure,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Terry Purcell,36,0,0.500000,568508.0,655533.00,425859.00,415754.0,349980.0,188400.0,0.800000,0.130435,0.0,517964.0,632387.00,328315.50,428095.0,762522.0,137520.0
17,Chris Brady,18,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Danny Vulich,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Joey Parker,13,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
all_time_leaderboard_stats.shape

(184, 19)

In [6]:
all_time_leaderboard_stats.columns.tolist()

['Player',
 'Total Games',
 'Total Maxouts',
 'Winning Percentage',
 'Fair Median Score',
 'High Range',
 'Low Range',
 'Fair Median 19 Trans',
 'Fair Median 29 Trans',
 'Fair Median Post',
 'Fair 19%',
 'Fair 29%',
 'Fair 38%',
 'Median Score',
 'Upper Quartile',
 'Lower Quartile',
 'Median 19 Trans',
 'Median 29 Trans',
 'Median Post']

In [7]:
all_time_leaderboard_stats.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Player                184 non-null    str
 1   Total Games           184 non-null    int64
 2   Total Maxouts         184 non-null    int64
 3   Winning Percentage    76 non-null     float64
 4   Fair Median Score     76 non-null     float64
 5   High Range            76 non-null     float64
 6   Low Range             76 non-null     float64
 7   Fair Median 19 Trans  76 non-null     float64
 8   Fair Median 29 Trans  72 non-null     float64
 9   Fair Median Post      76 non-null     float64
 10  Fair 19%              76 non-null     float64
 11  Fair 29%              76 non-null     float64
 12  Fair 38%              76 non-null     float64
 13  Median Score          76 non-null     float64
 14  Upper Quartile        76 non-null     float64
 15  Lower Quartile        76 non-null     float64
 16  Median 19 Trans       76 non-null     float64
 17  Median 29 Trans       72 non-null     float64
 18  Median Post           76 non-null     float64
dtypes: float64(16), int64(2), str(1)
memory usage: 27.4 KB

In [8]:
all_time_leaderboard_stats["Winning Percentage"].isna().sum()

np.int64(108)

In [9]:
all_time_leaderboard_stats[all_time_leaderboard_stats["Winning Percentage"].isna()].head(20)

,Player,Total Games,Total Maxouts,Winning Percentage,Fair Median Score,High Range,Low Range,Fair Median 19 Trans,Fair Median 29 Trans,Fair Median Post,Fair 19%,Fair 29%,Fair 38%,Median Score,Upper Quartile,Lower Quartile,Median 19 Trans,Median 29 Trans,Median Post
3,Robin Mihara,14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Dana Wilcox,10,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Bo Steil,11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Mike Winzinek,19,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Cameron Eure,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Chris Brady,18,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Danny Vulich,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Joey Parker,13,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Vince,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,TheMetalBeast,10,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Gin Morgan,8,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Schoolmaster,12,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,David Vulich,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Jake Stein,8,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Adam Cornelius,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Frank Westphal,7,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,SQR,10,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Rigel Pierce,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Sean Miller,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,KevinDDR,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
all_time_leaderboard_stats[all_time_leaderboard_stats["Winning Percentage"].notna()].head(10)

,Player,Total Games,Total Maxouts,Winning Percentage,Fair Median Score,High Range,Low Range,Fair Median 19 Trans,Fair Median 29 Trans,Fair Median Post,Fair 19%,Fair 29%,Fair 38%,Median Score,Upper Quartile,Lower Quartile,Median 19 Trans,Median 29 Trans,Median Post
0,Jonas,102,0,0.745098,636770.0,759390.00,513380.00,468503.0,177080.0,174460.0,0.954023,0.108108,0.0,577560.0,723200.00,461456.00,468645.0,932620.0,154770.0
1,Harry Hong,62,0,0.548387,574673.0,671366.75,450222.00,454572.0,372938.0,155283.0,0.888889,0.194444,0.0,528780.0,663476.50,429212.00,459080.0,697824.0,126580.0
2,Eli Markstrom,29,0,0.482759,474351.0,533979.00,385677.00,396031.0,350279.0,70511.0,0.875000,0.117647,0.0,411214.0,505763.00,350098.00,406637.0,692467.0,32523.0
4,Ben Mullen,22,0,0.363636,496853.0,585540.00,430900.00,459480.0,NaN,97140.0,0.809524,0.000000,0.0,479660.0,541367.25,414955.00,465180.0,NaN,75071.5
5,Buco,31,0,0.483871,498061.0,637859.25,346058.25,371661.5,320639.5,156050.0,0.777778,0.190476,0.0,434537.0,633990.00,329894.00,423706.5,757149.5,143480.0
7,Alex Kerr,54,0,0.462963,512860.0,617644.50,377925.00,432746.0,226100.0,137640.0,0.745098,0.058824,0.0,456090.0,583434.00,257510.00,440866.0,757933.0,117240.0
8,Josh Tolles,29,0,0.379310,484080.0,635966.25,405721.75,386961.5,NaN,165120.0,0.769231,0.047619,0.0,467074.0,631230.00,397819.00,424120.0,NaN,105220.0
9,Quaid,66,0,0.545455,583036.0,671818.25,443090.00,421206.0,644310.0,197613.0,0.877193,0.263158,0.0,555940.5,671818.25,418901.25,431831.0,802320.0,187600.0
12,Chad,28,0,0.464286,462010.5,534790.00,377005.00,401201.0,NaN,67740.0,0.909091,0.000000,0.0,439030.0,507840.00,351900.00,406700.0,NaN,29540.0
13,Jani Herlevi,33,0,0.393939,522624.5,602550.00,343140.00,399143.5,211665.0,97600.0,0.821429,0.142857,0.0,482200.0,592940.00,301120.00,418440.0,558187.0,77920.0

In [12]:
all_time_leaderboard_stats["Total Maxouts"].value_counts(dropna=False).sort_index()

Total Maxouts
0     94
1     22
2      6
3     11
4      5
5      3
6      4
7      5
8      2
9      2
10     2
11     2
12     4
13     2
15     2
16     1
17     1
19     1
20     2
22     2
23     1
24     1
28     1
33     2
40     1
42     3
45     1
67     1
Name: count, dtype: int64

In [13]:
all_time_leaderboard_stats["Total Maxouts"].describe()

count    184.000000
mean       4.869565
std       10.073194
min        0.000000
25%        0.000000
50%        0.000000
75%        4.250000
max       67.000000
Name: Total Maxouts, dtype: float64

In [14]:
all_time_leaderboard_stats["Total Maxouts"].max()

np.int64(67)

In [15]:
all_time_leaderboard_stats[all_time_leaderboard_stats["Total Maxouts"] > 0]

,Player,Total Games,Total Maxouts,Winning Percentage,Fair Median Score,High Range,Low Range,Fair Median 19 Trans,Fair Median 29 Trans,Fair Median Post,Fair 19%,Fair 29%,Fair 38%,Median Score,Upper Quartile,Lower Quartile,Median 19 Trans,Median 29 Trans,Median Post
28,Koryan,78,3,0.602564,729660.0,921580.00,590220.0,525220.5,934960.0,220360.0,0.957143,0.300000,0.0,694430.0,893655.00,541829.0,528120.0,963200.0,156860.0
47,JdMfX_,74,20,0.743243,989450.0,1058950.00,803730.0,545360.0,1029340.0,463120.0,0.936508,0.457143,0.0,940230.0,1057280.00,762080.0,557140.0,1044620.0,460980.0
48,Greentea,31,3,0.612903,868710.0,941710.00,780625.0,511560.0,887480.0,376130.0,0.928571,0.437500,0.0,868710.0,941710.00,772425.0,519370.0,910040.0,376130.0
51,Sharky,36,1,0.416667,744496.0,842317.25,495752.0,481362.0,902712.5,271740.0,0.909091,0.233333,0.0,741335.5,842317.25,494190.5,482272.5,914996.0,271740.0
55,Marq,41,1,0.487805,637170.0,802010.00,462106.0,447763.0,531530.0,239640.0,0.838710,0.217391,0.0,548860.0,802010.00,422020.0,462350.5,827905.0,237950.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,winterra,9,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,Bland,5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,AvGeekW159,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Bendy,6,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,shakeqc,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
all_time_leaderboard_stats.loc[
    all_time_leaderboard_stats["Total Maxouts"] > 0,
    ["Player", "Total Maxouts"]
].sort_values("Total Maxouts", ascending=False)

               Player  Total Maxouts
81   dogplayingtetris             67
90            Fractal             45
95       Huffulufugus             42
127            Alex T             42
110         PixelAndy             42
..                ...            ...
150          trapzone              1
135              moja              1
137            KofiOW              1
145             Draco              1
181           shakeqc              1

[90 rows x 2 columns]